# Generated by Django 5.2.5 on 2025-08-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cold', 'Cold'), ('Cough', 'Cough'), ('Fever', 'Fever'), ('Back Pain', 'Back Pain'), ('Neck Pain', 'Neck Pain'), ('Headache', 'Headache'), ('Acne', 'Acne'), ('Skin Rash', 'Skin Rash'), ('Child Fever', 'Child Fever'), ('Fracture', 'Fracture')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('General', 'General')], max_length=50)),
                ('rating', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('diseases', models.ManyToManyField(related_name='doctors', to='doctors.disease')),
            ],
        ),
    ]
